### ISSUE TITLE
Any trick to get around ssl certs?

### ISSUE THREAD

**Issue by rchannel** [sijis/err-salt#2]
Error I am getting.

Computer says nooo. See logs for details.:
[Errno 1] _ssl.c:510: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed

**Comment by sijis** [comment]
Is that on the salt master?

**Comment by rchannel** [comment]
No this it the error on the errbot terminal.  Is there a way to pass a argument to not check certs/ssl

**Comment by sijis** [comment]
In line #65 in salt.py, add this parameter to the pepper.Pepper statement
`ignore_ssl_errors=True`.
Let me know if that works.

**Comment by rchannel** [comment]
Ok guessing it works, sorry it took forever to have free time to test.  But now I am getting:
An error happened while processing a message ("!salt eagle test.ping"): Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/errbot/errBot.py", line 454, in _execute_and_send
    reply = commands[cmd](mess, match) if match else commands[cmd](mess, args)
  File "/usr/local/share/errbot/plugins/sijis/err-salt/salt.py", line 68, in salt
    self.config['api_auth'])
  File "/usr/local/lib/python2.7/dist-packages/pepper/libpepper.py", line 298, in login
    'eauth': eauth}).get('return', [{}])[0]
  File "/usr/local/lib/python2.7/dist-packages/pepper/libpepper.py", line 141, in req
    raise PepperException('Authentication denied')
PepperException: Authentication denied
"
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/errbot/errBot.py", line 454, in _execute_and_send
    reply = commands[cmd](mess, match) if match else commands[cmd](mess, args)
  File "/usr/local/share/errbot/plugins/sijis/err-salt/salt.py", line 68, in salt
    self.config['api_auth'])
  File "/usr/local/lib/python2.7/dist-packages/pepper/libpepper.py", line 298, in login
    'eauth': eauth}).get('return', [{}])[0]
  File "/usr/local/lib/python2.7/dist-packages/pepper/libpepper.py", line 141, in req
    raise PepperException('Authentication denied')
PepperException: Authentication denied

My auth is:
'api_auth': 'pam',

**Comment by sijis** [comment]
Are the username and password correct in the config? There is a way to validate the creds via curl and it'd have to be done from where you bot lives.

I don't remember the curl command offhand but I'll poke around and see if I find it.

**Comment by rchannel** [comment]
After restarting our salt-api service auth looks much better.

But after applying the In line #65 in salt.py, add this parameter to the
pepper.Pepper statement
ignore_ssl_errors=True.

10:44:23 INFO     errbot.plugins.ACLS       Matching ACL {} against
username @rick for command Salt:salt
10:44:23 INFO     errbot.plugins.ACLS       Check if salt is admin only
command.
10:44:23 INFO     errbot.errBot             Processing command 'salt' with
parameters 'eagle test.ping' from @rick
10:44:23 ERROR    errbot.errBot             An error happened while
processing a message ("!salt eagle test.ping"): Traceback (most recent call
last):
  File "/usr/local/lib/python2.7/dist-packages/errbot/errBot.py", line 454,
in _execute_and_send
    reply = commands[cmd](mess, match) if match else commands[cmd](mess,
args)
  File "/usr/local/share/errbot/plugins/sijis/err-salt/salt.py", line 68,
in salt
    self.config['api_auth'])
  File "/usr/local/lib/python2.7/dist-packages/pepper/libpepper.py", line
298, in login
    'eauth': eauth}).get('return', [{}])[0]
  File "/usr/local/lib/python2.7/dist-packages/pepper/libpepper.py", line
150, in req
    raise PepperException('Unable to parse the server response.')
PepperException: Unable to parse the server response.
"
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/errbot/errBot.py", line 454,
in _execute_and_send
    reply = commands[cmd](mess, match) if match else commands[cmd](mess,
args)
  File "/usr/local/share/errbot/plugins/sijis/err-salt/salt.py", line 68,
in salt
    self.config['api_auth'])
  File "/usr/local/lib/python2.7/dist-packages/pepper/libpepper.py", line
298, in login
    'eauth': eauth}).get('return', [{}])[0]
  File "/usr/local/lib/python2.7/dist-packages/pepper/libpepper.py", line
150, in req
    raise PepperException('Unable to parse the server response.')
PepperException: Unable to parse the server response.

**Comment by rick** [comment]
![](https://media.giphy.com/media/V6R9thgW7fimI/giphy.gif)
